/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MockupsRouteImport } from './routes/mockups'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'
import { Route as ShopCarrinhoRouteImport } from './routes/shop/carrinho'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as ShopPedidoOrderIdRouteImport } from './routes/shop/pedido.$orderId'

const MockupsRoute = MockupsRouteImport.update({
  id: '/mockups',
  path: '/mockups',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCarrinhoRoute = ShopCarrinhoRouteImport.update({
  id: '/shop/carrinho',
  path: '/shop/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPedidoOrderIdRoute = ShopPedidoOrderIdRouteImport.update({
  id: '/shop/pedido/$orderId',
  path: '/shop/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/mockups': typeof MockupsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/carrinho': typeof ShopCarrinhoRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/pedido/$orderId': typeof ShopPedidoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/mockups': typeof MockupsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/carrinho': typeof ShopCarrinhoRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop': typeof ShopIndexRoute
  '/shop/pedido/$orderId': typeof ShopPedidoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/mockups': typeof MockupsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/shop/carrinho': typeof ShopCarrinhoRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/pedido/$orderId': typeof ShopPedidoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design-system'
    | '/mockups'
    | '/shop/$productId'
    | '/shop/carrinho'
    | '/shop/checkout'
    | '/shop/'
    | '/shop/pedido/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/design-system'
    | '/mockups'
    | '/shop/$productId'
    | '/shop/carrinho'
    | '/shop/checkout'
    | '/shop'
    | '/shop/pedido/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design-system'
    | '/mockups'
    | '/shop/$productId'
    | '/shop/carrinho'
    | '/shop/checkout'
    | '/shop/'
    | '/shop/pedido/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DesignSystemRoute: typeof DesignSystemRoute
  MockupsRoute: typeof MockupsRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopCarrinhoRoute: typeof ShopCarrinhoRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopPedidoOrderIdRoute: typeof ShopPedidoOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mockups': {
      id: '/mockups'
      path: '/mockups'
      fullPath: '/mockups'
      preLoaderRoute: typeof MockupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/carrinho': {
      id: '/shop/carrinho'
      path: '/shop/carrinho'
      fullPath: '/shop/carrinho'
      preLoaderRoute: typeof ShopCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/pedido/$orderId': {
      id: '/shop/pedido/$orderId'
      path: '/shop/pedido/$orderId'
      fullPath: '/shop/pedido/$orderId'
      preLoaderRoute: typeof ShopPedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DesignSystemRoute: DesignSystemRoute,
  MockupsRoute: MockupsRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  ShopCarrinhoRoute: ShopCarrinhoRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopPedidoOrderIdRoute: ShopPedidoOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
